name: Continuous Integration

on: pull_request

env:
  DOCKER_BUILDKIT: 1
  TEST_TAG: gogaille/bref:test

jobs:
  bref:
    name: Build and test gogaille/bref image
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gogaille/bref
      - name: build
        uses: docker/build-push-action@v5
        with:
          context: ./bref
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: test
        run: |
          docker run --rm ${{ env.TEST_TAG }} php --version
          docker run --rm ${{ env.TEST_TAG }} composer --version
